### ISSUE TITLE
Are Item Templates Supported?

### ISSUE THREAD

**Issue by RehanSaeed** [sayedihashimi/template-sample#10]
Are Item Templates Supported? I've tried the files below and they don't work for me:

# template.json

```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": ".NET Boxed",
  "classifications": [
    "Config"
  ],
  "identity": "Dotnet.Boxed.gitattributes.CSharp",
  "name": ".gitattributes file",
  "shortName": "gitattributes",
  "defaultName": ".gitattributes",
  "description": "Controls Git settings like line endings, which files are treated as binary files and Git Large File System (LFS) settings.",
  "tags": {
    "language": "C#",
    "type": "item"
  }
}
```

Just realized I have the language set to C#. Not sure what should go there.

# ide.host.json

```json
{
  "$schema": "http://json.schemastore.org/vs-2017.3.host",
  "order": 0,
  "learnMoreLink": "https://github.com/Dotnet-Boxed/Templates",
  "icon": "icon.png"
}
```

**Comment by sayedihashimi** [comment]
They should be working. I haven't tried them myself though. We will need to wait until Phil comes back to take a look. I believe he is back on Monday.

**Comment by sayedihashimi** [comment]
@RehanSaeed you still having issues with item templates?

**Comment by RehanSaeed** [comment]
I don't see them appearing in VS.

**Comment by sayedihashimi** [comment]
Can you point me to the NuGet pkg and the item templates that are not showing up?

**Comment by RehanSaeed** [comment]
Same one as the project templates in https://www.nuget.org/packages/Boxed.Templates/.

**Comment by nils-a** [comment]
Sorry to jump on this issue. Is there any news?

**Comment by sayedihashimi** [comment]
Sorry I thought that I replied here, Item Templates are not supported yet.

**Comment by nils-a** [comment]
So... Is there a feature-request we can vote on? 😉

**Comment by RehanSaeed** [comment]
It seems item templates are still not supported in VS 2022.

**Comment by sayedihashimi** [comment]
@RehanSaeed we will have a way to add Item Templates to the New Item Dialog, but we are planning to change the mechanism to get those to appear when .net 7 ships. If we work with you to get your items appearing in the short term, you'll likely need to update when .net 7 rolls out. If that is OK with you, then let's start a mail thread on this topic. I believe you already have my email address, but let me know if you don't.
I'd like to avoid wide spread usage of this because we don't plan to support this long term (i.e. we will likely drop support for the current method when .net 7 goes out).

**Comment by RehanSaeed** [comment]
In that case I'd rather avoid using a preview of .NET 7.

**Comment by sayedihashimi** [comment]
@RehanSaeed you wouldn't need to use any preview versions of .net. To be more specific, you'll need to add some content to the `ide.host.json` in the short term. Later, if the work happens, in .net 7 you'll need to migrate the item template content from `ide.host.json` into a different form in `template.json`.

**Comment by sayedihashimi** [comment]
Question has been answered, closing.
