### ISSUE TITLE
Are solution templates supported

### ISSUE THREAD

**Issue by musictopia2** [sayedihashimi/template-sample#12]
There are many cases where several projects are needed at once.  An example of where its already done is blazor web assembly core hosted.  In that case, 3 projects are created each time.  That would be very important to be able to do.

**Comment by sayedihashimi** [comment]
We are having a conversation about this, take a look at my proposal at https://github.com/sayedihashimi/template-sample/issues/7#issuecomment-721388006. Let's continue the discussion there, please let me know if that works for you. I'll close this issue now.
