### ISSUE TITLE
Need ide.host.json Reference Wiki

### ISSUE THREAD

**Issue by CodeChaser** [sayedihashimi/template-sample#13]
Hello,

I have looked everywhere for this.  I even opened the schema to see if it would help.

In .vstemplate files there are 3 tags, "LanguageTag, ProjectTypeTag & PlatformTag.  Looking in the schema I came across uiFilters array.  That is just a guess, but how would I go about setting this in ide.host.json.

thx

**Update
Watching your video again, I heard you say "classifications" shows up where the "ProjectTypeTag" is used.

**Comment by sayedihashimi** [comment]
For the language in the [template.json](https://github.com/sayedihashimi/template-sample/blob/main/src/Content/MyCommand/.template.config/template.json#L10). For platform and project type, it depends on what you are trying to achieve with these. As you mentioned if you populate `classifications` users can filter on the well known values in Visual Studio.

If you can tell me what you're trying to accomplish it would be easier than trying to directly translate vstemplate. The code for the Template Engine is not based on vstemplate, so there may not be direct equivalents for all things.
