### ISSUE TITLE
Helpful Info (VS IDE) .. Maybe Known

### ISSUE THREAD

**Issue by CodeChaser** [sayedihashimi/template-sample#14]
Is this the best place to report discoveries and work arounds?
ide.host.json
- Does not work with "icon": "icon.**ico**"  not recognized.  Used a png extension no problem.

template.json
- "preferNameDirectory": true - did not add projects to solution, either existing or new
   - changed to "preferNameDirectory": false -> worked perfectly
   - added Solution folder first, projects showed up as expected

**Comment by sayedihashimi** [comment]
For the icon element I [added a note](https://github.com/sayedihashimi/template-sample/commit/39d54d0760406e3ff6735f5f93d4921e72c9bd0f) in the readme to indicate it should be a `.png` file.

About the `preferNameDirectory`, that sounds like a new issue. Can you give some more info so that I can try to reproduce it on my end?

**Comment by CodeChaser** [comment]
I missed the comment, sorry.

preferNameDirectory - I am still chasing, trying to figure out the behavior.  I will update here with "steps to recreate" once I flush it out.

**Comment by CodeChaser** [comment]
History
=====================
VS2019 16.5 -> upgrade 16.8.4
The following list of problems maybe to do with installation in VM, no other options are available for testing at work

Behavior 1
================
1. preferNameDirectory="true" or "false" makes no difference
2. No solution create project
3. Solution is created
4. Projects are created but not added to Solution
5. Create solution first
6. Add new project, projects get added

Behavior 2
================
1. "dotnet new --debug:reinit" clears dotnet template as expected
2. Dotnet new -l - shows template gone
3. Always VS2019 is closed, DO NOT OPEN
4. Make change to template, use project name with ending digit to determine when changes have been added to VS2019
5. Pack new Nuget
6. Dotnet new --install changed template
7. VS2019 shows Original templete, Dotnet new -l shows original project
8. Run "dotnet new --debug:reinit" again
9. Open VS2019, open "create new project", project is gone, as expected
10. Close vs2019
11. Install changed template
12. Open VS2019.. changed template now shows up
13. After running "dotnet new --debug:reinit" I have to open VS2019, create New project in order to refresh ? something

Behavior 3
================
1. sourceName only works with lowercase "endpoint" or "Endpoint"
2. sourceName does not work with "ENDPOINT"
3. ex:
4.     sourceName = "endpoint"  
5.     project name entered = "abc"
6.          ENDPOINTQuery _endpointQuery = new ENDPOINTQuery()
7.     result
8.          ENDPOINTQuery _abcQuery = new ENDPOINTQuery()

1. Further research of multiple online examples shows 
2. Namespaces, project file names using lowercase sourceName work as expected
3. No examples mixed Case in any examples or videos
4. Class/Interface objects are hardcoded replacement is not needed
4. When I used lowercase sourcename for all objects works perfectly
5: ex:
6.     endpointQuery _endpointQuery = new endpointQuery()
7. Result:
8.      abcQuery _abcQuery = new abcQuery()
9. works perfectly like all examples; some have Endpoint and work as well

Behavior 4
=============
1. all replacements of sourceName, if they work, are always in "lower case"
2. sometimes, some replacements do not work.

Behavior 5
=============
1. reset templates etc 
2. open VS2019 create project to ensure cache or ? whatever is cleared
3. install template
4. Create blank solution
5. Add project or folder then new project
6. First time in using "new template" project folder location matches root of solution
7. Adding a another project to solution takes you to the default repo source folder
8. You have to pick solution folder each time

1. My boss gave me until tomorrow, or I have to dropped what I did.  I wasted a week trying to take and dynamically update multiple objects as shown.
2. Is this a BKE "Behind Keyboard Error"?  who knows either way I failed at my task

** I added the .txt to allow it to be uploaded
[template.json.txt](https://github.com/sayedihashimi/template-sample/files/5816798/template.json.txt)

I am tired and feel I misunderstood the intent of this templating without tokenization.  I was expecting more results. 

Finally I am unsure if "symbol" casing will fix my challenge of using both upper n lower case for the sourceName 

Regards,
Tom Kelly

**Comment by sayedihashimi** [comment]
@CodeChaser I'm having a hard time understanding what you have posted here. If you are having different issues, I think it's best to create different issues for specific things that are not working.

It sounds like one issue that you are having is with replacements not working correct. Those types of bugs should be filed over at https://github.com/dotnet/templating/issues.

**Comment by CodeChaser** [comment]
Cool I give up.
