### ISSUE TITLE
Issues while using the Choice parameter in the conditions

### ISSUE THREAD

**Issue by jkarra2020** [sayedihashimi/template-sample#15]
Hello @sayedihashimi 

I am working on creating some custom templates using the choice parameters and been having some issues.

Here is the scenario I am using the choice parameter for -
I want to add a choice parameter called Logging, and the choices it would take is NLog, SeriLog, Log4Net. Based on the dotnet new CLI cmd options (dotnet new mycustomtemplate --Logging "NLog"), I want to add the required nuget packages in the csproj file, and may be some code to configure those loggers in the startup.cs file.

The issue I have is - 
When I try to add the condition like #if (Logging=="NLog") in the startup.cs file, it doesn't not consider it a condition, like how it does for bool parameters (for example if Logging was bool, then #if Logging works good, but not when it is choice parameter which takes some string values.)

would you be able to point to a sample if you already have one, or let me know how I could use the choice parameter in a condition.

startup.cs
#if Logging=="Nlog"
#endif

**Comment by jkarra2020** [comment]
Found your MyWebWithAuth sample, which solves my purpose. Thanks.

**Comment by sayedihashimi** [comment]
Ok glad you figured it out
