### ISSUE TITLE
 Update readme to show how to properly handle guids in .sln files

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/template-sample#17]

**Comment by sayedihashimi** [comment]
added at https://github.com/sayedihashimi/template-sample#how-to-create-a-multi-project-solution-template

**Comment by RehanSaeed** [comment]
If we don't do this, is there any negative side affects?

> Update template.json to create unique GUIDs to replace the Project ID in the .sln file.

**Comment by sayedihashimi** [comment]
@RehanSaeed If a user tries to add multiple projects into the same solution with the same ID, the behavior is undefined. There can also be issues if users work on different projects that have the same ID but a different source path. I'm not sure about all the details about what can go wrong, but it's always best to ensure that the project IDs are unique. It's pretty simple to get the GUIDs updated, it's just an array of IDs.
