### ISSUE TITLE
Is there a way to modify the title of the template as shown in VS?

### ISSUE THREAD

**Issue by nils-a** [sayedihashimi/template-sample#21]
Currently my title looks like this:

![image](https://user-images.githubusercontent.com/349188/116811519-1dc03f00-ab4a-11eb-9fde-b70d2508de32.png)

Which seems to be something like `$name ($author)` - however I don't see any other template containing the author field.
(The length of our author-filed makes this a bit more.. "ugly")

So: Is there a way to customize the appearance of that section?

**Comment by sayedihashimi** [comment]
I think it comes from the authors, or owners, listed in the NuGet package itself. We don't have a way to customize this. We've never seen such a long list of authors.

**Comment by nils-a** [comment]
Ok, thanks.
