### ISSUE TITLE
adding a non-existing TFM in the Framework symbol choices breaks template creation

### ISSUE THREAD

**Issue by nils-a** [sayedihashimi/template-sample#22]
I wanted to do something "special" so I created the following `symbol` for `Framework`:

```json
"Framework": {
    "type": "parameter",
    "description": "The target frameworks for the project.",
    "datatype": "choice",
    "choices": [
        {
            "choice": "netstandard2.0",
            "description": "Target netstandard2.0 only"
        },
        {
            "choice": "net5.0",
            "description": "Target netstandard2.0 and net5.0"
        },
        {
            "choice": "net461",
            "description": "Target netstandard2.0 and net461"
        },
        {
            "choice": "all",
            "description": "Target netstandard2.0, net461 and net5.0"
        }
    ],
    "defaultValue": "netstandard2.0"
}
```

While this works perfectly fine in CLI, VS "chokes" on building the options page and freezes.

Removing the "all" choice fixes the problem.

While I would love to have the above working I can live with a workaround. However, I feel that VS should not freeze on incorrect input.

**Comment by sayedihashimi** [comment]
@nils-a thanks for the report, would you happen to have a nupkg we can test with?

@phenning report of a VS hang.

**Comment by nils-a** [comment]
This is the broken version.
[Cake.Templates.0.0.1.nupkg.zip](https://github.com/sayedihashimi/template-sample/files/6437722/Cake.Templates.0.0.1.nupkg.zip)

**Comment by sayedihashimi** [comment]
I'm able to repro this issue.

@phenning internal work item id is 1324100

**Comment by RehanSaeed** [comment]
Related https://github.com/sayedihashimi/template-sample/issues/8

**Comment by sayedihashimi** [comment]
This has been fixed and will be included in the next VS preview.
