### ISSUE TITLE
Add a private extension gallery to Visual Studio for multiple devices in the organization

### ISSUE THREAD

**Issue by archubbuck** [sayedihashimi/template-sample#24]
Hi @sayedihashimi,

I am searching for a solution to update multiple devices in the organization to add a private extension gallery to Visual Studio. We would prefer to be able to update all devices with this setting in the background so that our developers don't need to manually add the gallery to their Visual Studio installation. 

In my research, I've seen that registry keys may have been used at some point to solve this particular situation. Is this still the recommended solution? If so, do you know of any documentation available that outlines this process?

If there is another way to accomplish this or if registry keys are no longer an option, I'd love to know!

**Comment by archubbuck** [comment]
For reference, this is the screen I'm referring to:
![image](https://user-images.githubusercontent.com/3529902/119560068-795ca180-bd71-11eb-97d9-f3e211849b6f.png)

**Comment by sayedihashimi** [comment]
@archubbuck I'm really not sure, maybe @madskristensen knows?

**Comment by madskristensen** [comment]
Here's how to add those registry keys from any extension: https://github.com/madskristensen/VsixGalleryExtension/blob/master/src/feed.pkgdef

**Comment by archubbuck** [comment]
Thanks @madskristensen. I'll take a look.

**Comment by archubbuck** [comment]
@madskristensen, please forgive my ignorance but is there a tool or utility that can be used to apply the pkgdef file?

**Comment by archubbuck** [comment]
@madskristensen, do you have any insight on the above?

**Comment by archubbuck** [comment]
@madskristensen, to avoid unwanted notifications, this will be the last time that I mention you but if you could provide me with any insight on this I would greatly appreciate it.

**Comment by madskristensen** [comment]
Just drop the .pkgdef in your VSIX project and register it as a Package assets in the .vsixmanifest file

**Comment by archubbuck** [comment]
@madskristensen correct me if I'm wrong here but that would only be beneficial to users if we were planning on programmatically installing this via the Visual Studio extension installer. What we're trying to accomplish is programmatically adding the custom extension gallery to their list of feeds before anything is installed at all.

**Comment by sayedihashimi** [comment]
Closing this since it’s not related to templates.
