### ISSUE TITLE
Choice parameters are not well binded in Visual Studio Template

### ISSUE THREAD

**Issue by wlidha81** [sayedihashimi/template-sample#28]
Hello,
i recently worked on a custom template for vs studio 2019, where i have set some custom choice parameters.
with Cli mode every thing works perfectly. Now when i tried to integrate the template in VStudio (ide.host.json), i have referenced the choice parameter name from ide.host.json.
I've noticed that the template wizard displays a drop down list correctly but items values and texts are not displayed correctly:
example: parameter name : param1 with choices: item1, item2.
In Vstudio wizard the drop down list contains two itemps with text = param1.
there should be an issue while binding choice parameters.

I would like also to have an example of multiple project templates with a choice parameters that works well in Visual Studio. Is it possible to have such sample ? 
Thanks a lot for your great job

**Comment by sayedihashimi** [comment]
Please share your template, or a new one that shows the same bug. I'll investigate.

**Comment by wlidha81** [comment]
- in template.json

"symbols": {

"Department": {
      "type": "parameter",
      "description": "The department.",
      "datatype": "choice",
      "choices": [
        {
          "choice": "IT",
          "description": "IT department"
        },
        {
          "choice": "HR",
          "description": "HR department"
        }
      ],
      "replaces": "DepartmentName",
      "defaultValue": "IT"
    },
......
}


in ide.host.json:
...
"symbolInfo": [
    {
      "id": "Department",
      "name": {
        "text": "The department"
      },
      "isVisible": "true"
    }
...

**Comment by wlidha81** [comment]
i've found the issue, in ide.host.json i should not mention "name" property. We should only specify the id + isVisible for choice paramters.
I'll close the issue sorry for that. :)
