### ISSUE TITLE
[Q] Is there a way of converting .vstemplate files?

### ISSUE THREAD

**Issue by ivanpovazan** [sayedihashimi/template-sample#30]
I was wondering is there a way to generate template.json from an existing .vstemplate file?
And if there isn't, what would be the preferred approach of upgrading them?

To provide you with more context:
We have a Visual Studio extension which provides custom project templates targeting .NET framework which need to be extended/upgraded to target .NET core as well.

**Comment by sayedihashimi** [comment]
Hi @ivanpovazan there isn't any way to convert from a vstemplate template to a Template Engine (dotnet new) style template. I think the easiest thing to do is to create a new project from your template, and then add the `.template.config` folder along with `template.json` and other files that you need.

**Comment by ivanpovazan** [comment]
Thank you for the answer!
