### ISSUE TITLE
Solution Template Bug

### ISSUE THREAD

**Issue by bugrakosen** [sayedihashimi/template-sample#32]
Hi,

I try to create my own solution template. I'm facing an infuriating bug or my mistake. I've watched this [mini serie](https://www.youtube.com/watch?v=H_pqfeRgTYw&list=PLBWnJhOsSsxGdqct18m4hr5Sk4ACv06hV&index=7&t=1s) on youtube and i read the [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates) . Then i applied same things my project. I've updated my template to NuGet and run `dotnet new -i <PackageId>` command results is as follow; 

![Capture](https://user-images.githubusercontent.com/32344242/121824392-a0452e00-ccb4-11eb-9eac-f8c16848b99c.PNG)

No errors and where is my package?

My [source code](https://github.com/Milvasoft/MilvaTemplate) and [nuget link](https://www.nuget.org/packages/Milvasoft.Templates.Web.Ef/) is available. Please check it out and help. Thank you.

**Comment by sayedihashimi** [comment]
Did you run the analyzer to see if it reports any errors/warnings?

**Comment by bugrakosen** [comment]
Yes i ran it and all fine. I forgot to mention that story.

![Capture](https://user-images.githubusercontent.com/32344242/121827629-6cbecf80-ccc5-11eb-9b1d-6f47d4d823ac.PNG)

**Comment by h3rmanj** [comment]
Seems to me that the problem is how it's packed. You need a parent .csproj or .nuspec which describes the package, and the template folder needs to be included as content in the package.

See https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack#build-and-install for reference folder structure and package `csproj` example.

**Comment by sayedihashimi** [comment]
@bugrakosen can you share the template?

**Comment by bugrakosen** [comment]
> Seems to me that the problem is how it's packed. You need a parent .csproj or .nuspec which describes the package, and the template folder needs to be included as content in the package.
> 
> See https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack#build-and-install for reference folder structure and package `csproj` example.

That is my solution. I finally figured out how to pack my solution. Thank you for your helps.
