### ISSUE TITLE
Additional information dialogue in Visual Studio is empty when Framework is not defined in symbols

### ISSUE THREAD

**Issue by Graicc** [sayedihashimi/template-sample#33]
Without Framework symbol in `template.json`, the "Additional information" tab in Visual Studio (Community 2019 Version 16.8.3) is blank, despite the `ide.host.json` file containing info:
![image](https://user-images.githubusercontent.com/33105645/123009180-3f8bb480-d38a-11eb-8bdc-46fa401bee98.png)

Adding 
```
"Framework": {
  "type": "parameter",
  "description": "The target framework for the project.",
  "datatype": "choice",
  "choices": [
    {
      "choice": "netstandard2.0",
      "description": "Target netstandard2.0"
    }
  ],
  "replaces": "netstandard2.0",
  "defaultValue": "netstandard2.0"
},
```
under symbols in `template.json` fixes the issue, and the "Additional information" tab has all the fields defined in `ide.host.json`.
![image](https://user-images.githubusercontent.com/33105645/123009270-65b15480-d38a-11eb-8db6-ac6661acc14a.png)

**Comment by sayedihashimi** [comment]
This has been fixed in later releases of Visual Studio. I know for sure it’s in 16.10, but maybe also 16.9.

**Comment by sayedihashimi** [comment]
I'm closing this because this should be fixed in the latest release, if you are still having issues with the latest release, please reopen this issue.
