### ISSUE TITLE
VSIX not working

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/template-sample#37]
The VSIX at https://www.dropbox.com/s/1hvvk6p7buuk3yy/MicroService.zip?dl=0 looks like it has all the right content to work. I couldn't figure out why it's not working.

@phenning can you take a look to see what's going on with this vsix?

This issue is a continuation of the discussion at the bottom of https://github.com/sayedihashimi/template-sample/issues/19 with @vondwater.

@vondwater FYI from the sources that you sent me, I made one change. That was to mark the `Templates.pkgdef` to be included in the VSIX. I think this is missing from the readme. I will get it updated. See the image below. In addition I noticed that your template name ends with "nuspec", that was an error in my sample. You should remove that after we figure out what is happening with this VSIX.

![image](https://user-images.githubusercontent.com/1283154/125497311-08e18458-9015-408b-abd6-7482c86b8621.png)

**Comment by phenning** [comment]
The version currently on drop box worked for me:

![image](https://user-images.githubusercontent.com/2433750/125704411-f0ff15b1-6311-4173-bc4e-9fa56e8a56c5.png)

**Comment by phenning** [comment]
Note that it worked both on the current 16.10 and on the 16.11 preview.

**Comment by sayedihashimi** [comment]
Thanks Phil, I will give it another shot tomorrow and see if it appears or not.

**Comment by vondwater** [comment]
@sayedihashimi I also successfully installed the project template like @phenning mentioned. So the only thing I forgot was the import in vsix option on the pkgdef file?

Thanks already for the effort!

**Comment by sayedihashimi** [comment]
@vondwater great to hear. I'll go ahead an close this out. Yes the only change that I made was to mark the Templates.pkgdef as IncludeInVSIX. I'll get that added to the readme.
