### ISSUE TITLE
Solution Template: Open file in editor 

### ISSUE THREAD

**Issue by bboy77** [sayedihashimi/template-sample#38]
When creating a project template, Visual Studio opens one or more files  using the primaryOutputs and postActions properties. 

This only works in a solution template when the files are at the same level as the solution file. If a project or multiple projects are nested, specific files are not opened.

**Comment by sayedihashimi** [comment]
Hi @bboy77 this feedback is better suited for the VS Dev community. It would be great if you could use [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) to report this so that we can track it.
