### ISSUE TITLE
Using a Wizard with dotnet new project templates

### ISSUE THREAD

**Issue by UmaHarano** [sayedihashimi/template-sample#44]
@sayedihashimi

Can you associate a Microsoft.VisualStudio.TemplateWizard.IWizard with the new dotnet new project templates?
If not, is there an equivalent mechanism?

I am currently using an IWizard with my templates authored using .vstemplate. I would like to switch to the new mechanism.

**Comment by sayedihashimi** [comment]
In the readme there is a section on how to execute the templates as a part of a VSIX. You can add a custom wizard to that. Let me know if you have more questions.

**Comment by UmaHarano** [comment]
Thank you! I will check that out.

**Comment by sayedihashimi** [comment]
I will close this, but if you run into any issues please open new issues with details of the issues.
