### ISSUE TITLE
Show how to add a Choice Parameter Type

### ISSUE THREAD

**Issue by RehanSaeed** [sayedihashimi/template-sample#5]
I have the following symbol in my `template.json` file:

```json
    "SourceControl": {
      "type": "parameter",
      "datatype": "choice",
      "choices": [
        {
          "choice": "GitHub",
          "description": "Adds a .github directory containing a code of conduct, contributing guide, pull request template and issue templates."
        },
        {
          "choice": "None",
          "description": "No source control provider is being used."
        }
      ],
      "defaultValue": "GitHub",
      "description": "Select which source control provider you are using if any, to add provider specific features."
    },
    "GitHub": {
      "type": "computed",
      "value": "(SourceControl == \"GitHub\")"
    },
```

This shows as follows in the VS UI:

![image](https://user-images.githubusercontent.com/2270364/97972838-0e3f8380-1dbd-11eb-9ca0-be090d05ff2d.png)

How can I show the correct labels for the items in the dropdown? This is my `ide.host.json`:

```json
{
  "$schema": "http://json.schemastore.org/vs-2017.3.host",
  "learnMoreLink": "https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/API.md",
  "icon": "icon.png",
  "symbolInfo": [
    {
      "id": "SourceControl",
      "name": {
        "text": "Source Control"
      },
      "isVisible": true
    },
  ]
}
```

When I remove the custom label `"text": "Source Control"` then I get this:

![image](https://user-images.githubusercontent.com/2270364/97973146-8efe7f80-1dbd-11eb-94e3-8ff85048c77d.png)

The label is now showing as `SourceControl` without the space.

**Comment by sayedihashimi** [comment]
It's working in my sample template, not sure why it's not working for you. Changes are in this branch https://github.com/sayedihashimi/template-sample/tree/2020.11.03/displayname.

![image](https://user-images.githubusercontent.com/1283154/98033643-d1d34e00-1de3-11eb-89ec-9f4bb6c0c733.png)

**Comment by RehanSaeed** [comment]
As mentioned in https://github.com/sayedihashimi/template-sample/issues/8 the `Framework` parameter seems to be special cased, so it's drop down works.

If you have any other `choice` symbol types (See my `SourceControl` symbol above), then this does not work. In my first screen shot, the items in the drop down both just say `SourceControl` i.e. they repeat the symbol name.

**Comment by bboy77** [comment]
I have the exact same issue as well for a custom symbol using the choice datatype. The choices show up fine when adding the symbol to a dotnetcli.host.json  file and using dotnet new. After template creation the choice shows up fine in all files that are part of the template.

However, only the text field is present in the IDE drop-down. Other non-choice symbols are working fine.

Is there any update on this?

Thanks

**Comment by Capsup** [comment]
Encountered exactly the same issue with a "choice" symbol, that _isn't_ framework. @sayedihashimi

**Comment by sayedihashimi** [comment]
Thanks, I understand that Choice parameters cannot have customized labels in VS. I've filed an internal bug for this, ID is 1342518.

**Comment by phenning** [comment]
This should be fixed in the current Preview 2 release of 16.11.

**Comment by RehanSaeed** [comment]
@phenning Is there an example of how to implement the custom label?

**Comment by phenning** [comment]
We basically fixed the bug where if you would have a host override for the choice control itself, we would apply the same override to each choice parameter as well. This bug is fixed, so you can now just provide the override of the choice parameter name itself, and if you do not supply overrides for each individual choice, we will just use what is defined in template.json.

You can provide overrides for one or all individaul choices, just like for individual symbols. 

Given the following symbol in template.json:
```
    "ChoiceParameter": {
      "type": "parameter",
      "description": "A sample choiceParameter",
      "datatype": "choice",
      "choices": [
        {
          "choice": "choice1",
          "description": "choice 1 description"
        },
        {
          "choice": "choice2",
          "description": "choice 2 description"
        }
      ],
      "replaces": "mychoice",
      "defaultValue": "choice1"
    },    
```
     

You can override this in the host file in the symbolInfo object via the following host file:
Note that the descriptions for individual choices are not currently used in Visual Studio. The description on parameter itself though is used to populate the tooltip.

```
"symbolInfo": [
    {
      "id": "ChoiceParameter",
      "name": {
        "text": "Sample _choice option"
      },
      "choices": [
        {
          "id": "choice1",
          "name": {
            "text": "my choice 1 "
          }
        }
      ]
      "isVisible": "true"
    }
]

```

**Comment by sayedihashimi** [comment]
FYI this should be fixed in the next preview

**Comment by bboy77** [comment]
See below

I am looking to replace "LicenseIdentifier" text with "License Identifier". The choices still only appear if I remove the "name" parameter in ide.host.json. The choices show fine but I wanted the display name of the parameter "LicenseIdentifier" in VS to have the space - "License Identifier". 

Adding the choices in ide.host.json made no difference in allowing the space to show .

template.json
```
"LicenseIdentifier": {
			"choices": [
				{
					"choice": "Apache-2.0",
					"description": "Apache License 2.0"
				},
				{
					"choice": "BSD-3-Clause",
					"description": "BSD 3-Clause \"New\" or \"Revised\" License"
				},
				{
					"choice": "GPL-3.0",
					"description": "GNU General Public License v3.0"
				},
				{
					"choice": "MIT",
					"description": "MIT License"
				},
				{
					"choice": "Unlicense",
					"description": "The Unlicense"
				}
			],
			"datatype": "choice",
			"defaultValue": "MIT",
			"description": "The license for the project.",
			"isRequired": false,
			"replaces": "$LICENSE_IDENTIFIER$",
			"type": "parameter"
		}
```

ide.host.json
```
{
			"choices": [
				{
					"id": "Apache-2.0",
					"isVisible": "true",
					"name": {
						"text": "Apache-2.0"
					}
				},
				{
					"id": "BSD-3-Clause",
					"isVisible": "true",
					"name": {
						"text": "BSD-3-Clause"
					}
				},
				{
					"id": "GPL-3.0",
					"isVisible": "true",
					"name": {
						"text": "GPL-3.0"
					}
				},
				{
					"id": "MIT",
					"isVisible": "true",
					"name": {
						"text": "MIT"
					}
				},
				{
					"id": "Unlicense",
					"isVisible": "true",
					"name": {
						"text": "Unlicense"
					}
				}

			],
			"id": "LicenseIdentifier",
			"isVisible": "true",
			//"name": {
			//	"text":  "License Identifier"
			//}
		}
```

**Comment by bboy77** [comment]
this provides the same result as above
```
{
    "id": "LicenseIdentifier",
    "isVisible": true
}
```

**Comment by sayedihashimi** [comment]
@bboy77 the fix is in but it hasn't been released yet. It should be in the next preview.

**Comment by bboy77** [comment]
I found a workaround. If you add a space in the property name itself, it works. 

![image](https://user-images.githubusercontent.com/74476132/125104391-f3878200-e0a2-11eb-94bb-5b3c3419b59b.png)


template.json
```
"License    Identifier": {
            "choices": [
                {
                    "choice": "Apache-2.0",
                    "description": "Apache License 2.0"
                },
                {
                    "choice": "BSD-3-Clause",
                    "description": "BSD 3-Clause \"New\" or \"Revised\" License"
                },
                {
                    "choice": "GPL-3.0",
                    "description": "GNU General Public License v3.0"
                },
                {
                    "choice": "MIT",
                    "description": "MIT License"
                },
                {
                    "choice": "Unlicense",
                    "description": "The Unlicense"
                }
            ],
            "datatype": "choice",
            "defaultValue": "MIT",
            "description": "The license for the project.",
            "isRequired": false,
            "replaces": "$LICENSE_IDENTIFIER$",
            "type": "parameter"
        }
```

ide.host.json
```
{
            "id": "License    Identifier",
            "isVisible": "true"
            // removed the text property
            //"text": "License    Identifier"
        }
```

**Comment by bboy77** [comment]
In addition to my post above, a dotnetcli.host.json file should be added to the .template.config folder. This is need for the display value of a `property` to be the same in cli and vs.

dotnetcli.host.json
```
"License    Identifier": {
    "isHidden": false,
    "longName": "license-identifier",
    "shortName": "li"
```

**Comment by sayedihashimi** [comment]
I’m closing this because Choice params, as well as other types, are showing automatically in VS2022. If there are other issues, please open a new issue. I’m trying to clean up the issues in this repo.
