### ISSUE TITLE
Solution file naming suggestion for wiki

### ISSUE THREAD

**Issue by phenning** [sayedihashimi/template-sample#51]
Update the docs to include guidance on naming the sln file in template something other then sourceName.sln or defaultName.sln to avoid reload prompt in Visual Studio when the Place solution and project in same folder is checked.

To preserve sourceName.sln naming for dotnet new, a rename can be provided:

If renaming the file in the template, the following source modifier can be used to rename it when created via dotnet new
```
          "condition": "(HostIdentifier == \"dotnetcli\" ||  HostIdentifier == \"dotnetcli-preview\")",
          "rename": {
            "Application1.app.sln": "Application1.sln"
          }
```

Alternatively, if keeping the sln file as Application1.sln in the template , the following source modifier can be used to rename it when created via Visual Studio to avoid the conflict
```
          "condition": "(HostIdentifier != \"dotnetcli\" &&  HostIdentifier != \"dotnetcli-preview\")",
          "rename": {
            "Application1.sln": "Application1.app.sln"
          }
```

**Comment by sayedihashimi** [comment]
Thanks Phil, added in e730cf61333b434616b4723492d764ed4341b5cc. When you get a chance, please take a look. I'll go ahead and close this, but if we need to update that let me know.
