### ISSUE TITLE
Instantiating VS template with correct solution

### ISSUE THREAD

**Issue by dositec** [sayedihashimi/template-sample#59]
Hello Sayed,
Would you help me again please?
I have created nuget template for VS with the following structure:
```
- "Content" folder:
              - "Sources" subfolder
                      -  any code files......
                      - .sln file
              - Dockerfile
              - .......
```
How I can reproduce same structure after expanding of template via Visual Studio?
Currently in the best variant(when the "Place solution and folder in the same directory" checkbox enabled): VS will generate extra .sln file in one level with "Sources" folder and open it in VS. But I need open my .sln file(in "Sources" folder) and prevent new .sln generation.

**Comment by sayedihashimi** [comment]
From within VS we don't have good support for these types of scenarios unfortunately. We had a discussion regarding this over at https://github.com/sayedihashimi/template-sample/issues/31.
