### ISSUE TITLE
Enable showing parameter descriptions in the New Project Dialog

### ISSUE THREAD

**Issue by RehanSaeed** [sayedihashimi/template-sample#6]
I have several custom parameters for which I have provided descriptions in my `template.json` file. This appear when using the CLI. However, in Visual Studio they do not. Is it possible to get them to show up?

![image](https://user-images.githubusercontent.com/2270364/97973862-a25e1a80-1dbe-11eb-90a2-0b1152b69dfc.png)

E.g. I have the following in `template.json` for the `Title` parameter:

```json
    "Title": {
      "type": "parameter",
      "datatype": "string",
      "defaultValue": "Project Title",
      "replaces": "PROJECT-TITLE",
      "description": "The name of the project which determines the NuGet package name and assembly product name."
    },
```

It would be nice if the `description` could be used in the UI somehow.

Secondly, I have a **lot** of parameters. Is there a way that I could group related parameters together somehow?

**Comment by sayedihashimi** [comment]
Can you share the source files for the template?

**Comment by RehanSaeed** [comment]
Sure, I have a PR up here to add VS support https://github.com/Dotnet-Boxed/Templates/pull/836

**Comment by RehanSaeed** [comment]
Also updated the issue above with more details about the description I'm talking about.

**Comment by sayedihashimi** [comment]
OK I see what you mean now. We do not currently have the ability to show descriptions for the parameters.

We are considering adding an info icon tooltip, would that work for you? Here is a sample mockup that I put together for your template. Would that work for you?

![info-icon](https://user-images.githubusercontent.com/1283154/98019699-1228d100-1dd0-11eb-9f61-22dd1cc7bc91.png)

cc @vijayrkn  @phenning

**Comment by sayedihashimi** [comment]
Added a new issue to track the grouping over at https://github.com/sayedihashimi/template-sample/issues/9

**Comment by RehanSaeed** [comment]
The info tooltips would be perfect!

**Comment by sayedihashimi** [comment]
FYI I changed the title

**Comment by RehanSaeed** [comment]
This is done.
