### ISSUE TITLE
How to ignore preprocessor configuration for dotnet template expanded code?

### ISSUE THREAD

**Issue by dositec** [sayedihashimi/template-sample#60]
I have a template with the following code:

```
var a =
#if DEBUG
    "Debug";
#else
    "Release";
#endif
```

After expansion I have:
```

var a =
    "Release";


```
What settings should I set so my template expands without any preprocessor changes?

**Comment by sayedihashimi** [comment]
Hi @dositec see the wiki which covers this https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#ignore-conditions-expressions-in-language-files. If that's working for you, please close this issue, and if not please let me know what's happening.

**Comment by dositec** [comment]
Hello, thank you for the link, I have corrected my template with help of the following comments, ant it helped me:
```
//-:cnd:noEmit

//+:cnd:noEmit
```
To be honest, I expect the C# preprocessor to don't work by default, in my template. It may be my suggestion, but it's up to you. Also thank you for the fast support help, I think new template engine it's cool feature, but I feeling a lack of real examples for difficult templates cases, for me it was sln template.

**Comment by sayedihashimi** [comment]
@dositec there is a sln sample in this repo at https://github.com/sayedihashimi/template-sample/tree/main/src/Content/SolutionTemplate as well as doc in the readme here.

I think the questions have been answered, so I'll close this issue. If not, please reopen with whatever questions you still have here.
