### ISSUE TITLE
Remove source control configuration from generated projects

### ISSUE THREAD

**Issue by mattkirschner** [sayedihashimi/template-sample#66]
My template project is connected to TFS source control and I'm having a heck of a time removing all the related bindings from new projects using this template. Right now, creating a new project results in a prompt stating that "The solution you are opening is bound to source control on...".

Is there any documentation that explains how and what to exclude in order to prevent new projects from retaining the template source control info? It seems that simply including ".vs/**" and "**/*.vspscc" in the source->modifiers->exclude array of template.json is not sufficient.

**Comment by mattkirschner** [comment]
Looking into this a little more, the issue seems to be with a few lines in the .sln file that need to be removed. Is there any documentation on how to edit the solution file during template install?

**Comment by sayedihashimi** [comment]
Hi, I think this would be better asked over at https://github.com/dotnet/templating/issues. We will need their help to answer this particular question.

**Comment by mattkirschner** [comment]
Ah, thanks - I didn't even think to look there. New issues here: https://github.com/dotnet/templating/issues/5544

**Comment by sayedihashimi** [comment]
Thanks. We discuss some issues here, but this is beyond the scope of what we can help with here.
