### ISSUE TITLE
HostIdentifier symbol needs binding

### ISSUE THREAD

**Issue by markwaterman** [sayedihashimi/template-sample#68]
This is very helpful repository for a beginner like me, thanks for writing all this up.

There's one thing I stumbled on in the readme's discussion of best practices for naming solution files:

https://github.com/sayedihashimi/template-sample/blob/e3488b473b0513a4a3ef168eb94f5939bf33ccb3/README.md?plain=1#L439

It would be worth mentioning that the `HostIdentifier` used in the rename condition won't work unless you also add it as a symbol:

```
  "symbols": {
    "HostIdentifier": {
      "type": "bind",
      "binding": "HostIdentifier"
    }
  }
```

...without this, the condition always evaluates to false.

**Comment by sayedihashimi** [comment]
Adding @phenning to see what he thinks of this suggestion.

**Comment by phenning** [comment]
Makes sense, you definitely need the bind as  you authored it if you want to use it in a condition. 

+1

**Comment by sayedihashimi** [comment]
@markwaterman  any chance you couldn’t send a PR? I’m totally swamped at the moment.
