### ISSUE TITLE
Templates That Already Contain a Solution

### ISSUE THREAD

**Issue by RehanSaeed** [sayedihashimi/template-sample#7]
All my project templates contain a solution and multiple project files. When I create a project using VS, it creates a new solution for me and does not open the one in the template. Is there a way to hide and disable the 'Solution name' text box below? 

![image](https://user-images.githubusercontent.com/2270364/98007013-cd5e6380-1dea-11eb-91ca-a5916aeb589f.png)

I've added VS support to my template in this PR: https://github.com/Dotnet-Boxed/Templates/pull/836 if you want to try it.

**Comment by sayedihashimi** [comment]
What would be the expected behavior if the user has an existing solution and then adds your template into that solution?

**Comment by RehanSaeed** [comment]
I would expect VS to take the contents of the solution in the template, add it to the current solution, then delete the solution from the template. 

Is this doable before release of this feature? I don't think my templates would be usable without it.

**Comment by sayedihashimi** [comment]
I don't think we would pursue merging the contents of the .sln on disk into the loaded solution. I think the best we could do is to search for project files and then load them.

For the case where a solution is not present, we should probably load the .sln file instead of the projects. I'll need to discuss with @phenning when he is back to work.

**Comment by RehanSaeed** [comment]
> I don't think we would pursue merging the contents of the .sln on disk into the loaded solution. I think the best we could do is to search for project files and then load them.

Would there be some way for me to detect this and tell the user not to use the template with an existing solution?

> For the case where a solution is not present, we should probably load the .sln file instead of the projects. I'll need to discuss with @phenning when he is back to work.

That would be ideal.

**Comment by sayedihashimi** [comment]
@RehanSaeed right now, I'd like to focus on getting the experience working when there is no existing solution file. I believe (correct me if I'm wrong), that will be the main usage of your template.

Here is what I'm thinking.

- In `template.json` the value for primaryOutputs should point to a .sln file
- In `template.json` set `$.tags.type` to `solution` (currently we only support `project` and `item`)
- When the template is used without adding to an existing solution, after the template is executed we load the .sln file
- When the template is used, and being added to an existing solution, after the template is executed we would search for project files and load them

If we add the metadata of `$.tags.type=solution`, then perhaps we can use that to enable showing a warning message like you mentioned.

**Comment by RehanSaeed** [comment]
That sounds like a sensible plan of action.

**Comment by phenning** [comment]
> I don't think we would pursue merging the contents of the .sln on disk into the loaded solution. I think the best we could do is to search for project files and then load them.
> 
> For the case where a solution is not present, we should probably load the .sln file instead of the projects. I'll need to discuss with @phenning when he is back to work.
 


> @RehanSaeed right now, I'd like to focus on getting the experience working when there is no existing solution file. I believe (correct me if I'm wrong), that will be the main usage of your template.
> 
> Here is what I'm thinking.
> 
> * In `template.json` the value for primaryOutputs should point to a .sln file
> * In `template.json` set `$.tags.type` to `solution` (currently we only support `project` and `item`)
> * When the template is used without adding to an existing solution, after the template is executed we load the .sln file
> * When the template is used, and being added to an existing solution, after the template is executed we would search for project files and load them
> 
> If we add the metadata of `$.tags.type=solution`, then perhaps we can use that to enable showing a warning message like you mentioned.

If we implement what you suggest above, I don't think we would need the warning in that case, would we?

I need to investigate this more after I get back, but we need to see if there are any issues with unloading the solution that was created for us by the IDE and then loading the one created by the template, especially around save/unload prompts.

**Comment by sayedihashimi** [comment]
FYI I have added an internal work item (ID: 1242270) to track this work.

**Comment by RehanSaeed** [comment]
Duplicate of https://github.com/sayedihashimi/template-sample/issues/16

**Comment by sayedihashimi** [comment]
@RehanSaeed #16 is a different issue. The idea with @16 is to update the analyzer to check for guid replacements in .sln files, and if not defined to raise a warning. I think with the implementation we have, we don't need to check for that any longer.

This issue is to discuss solution support in general. I think it's better to have the discussion on this issue, instead of 16.

> Does the older VS 16.9 or the .NET 5 CLI handle type="solution" nicely?

Support for `type="solution"` will be in the ***16.10 Preview 2*** release.

I think 16.9 doesn't show "solution" templates. For the CLI there is no impact.

**Comment by RehanSaeed** [comment]
Cool, in that case I'll wait for the official 16.10 release before deploying my change.

**Comment by sayedihashimi** [comment]
@RehanSaeed when the preview comes out it would be great if you can try your template and let us know if you run into any issues.

**Comment by h3rmanj** [comment]
I'm currently on 16.10.1, and I can't find templates with "type": "solution". Did the feature not ship?

**Comment by sayedihashimi** [comment]
@h3rmanj there should not be any such limitations, please share your nuget package so that I can take a look. Also if you haven't already run my template analyzer on your nuget package and see if it gives you any errors/warnings https://github.com/sayedihashimi/template-sample#template-analyzer

**Comment by h3rmanj** [comment]
It's [Intility.Templates](https://www.nuget.org/packages/Intility.Templates/), which should contain two templates; `iwebapi` (solution) and `iwebapiproject` (project). Running the analyzer I get the following warning for the template with `"type": "solution"`:  
`WARNING: Unable to determine if the template is for a project or item (file), assuming it is a project template`

I'm able to list them out individually by running `dotnet new --type solution` or `dotnet new --type project`, but in Visual Studio (and also with `dotnet new --list`) I'm only able to see one.

What I'm actually trying to achieve however, is including files which should be at the root of the output. I always want `.gitlab-ci.yml` and `README.md` to be in the root. When I'm only creating a project, I want it in the same folder as the `csproj`, but if I'm creating a solution, I want them besides the `sln`. Currently I need two templates for that, but I wish it was possible with one. It's mostly a problem with Visual Studio as it is the one creating the solution which might be in the parent or the same folder as the `csproj`. It should be it's own issue however, but I don't know what repo to put it in, as it seems as both this repo and dotnet/templating is used for template issue tracking?

**Comment by sayedihashimi** [comment]
@h3rmanj I updated the analyzer, there was a piece of code that wasn't updated for solution support. 

The reason why you're only seeing one of your templates is because the value for `groupIdentity` is the same. They should be unique. `groupIdentity` should be the same when you want multiple templates to be represented as the same template, and then differentiated by parameters passed by the user.

For the last part of your question, I think it's better to ask that over at https://github.com/dotnet/templating

**Comment by sayedihashimi** [comment]
@h3rmanj forgot to mention, I published version `1.0.7` of the analyzer that should work with solution templates now.

**Comment by h3rmanj** [comment]
Thanks! No warnings now 👍 Would be cool if it showed info when multiple templates use same `groupIdentity` as well, if it's possible. I'll stop noising this issue now however 🙂

**Comment by sayedihashimi** [comment]
@h3rmanj it's totally valid for more than one template to have the same `groupIdentity` value, it's designed for that actually. I gave a valid scenario for it in one of my previous comments. In order to properly check for that I'd have to know the intent of the template author.

**Comment by h3rmanj** [comment]
Yeah I realize that, but it's hard to come by info on all these options. I just copied the default aspnetcore one without knowing to much. This repo and tool has been insanely useful, thought it would be a nice addition for debugging. I meant info, as in not warning/error, just to make that clear. But it's up to you if that's something you'd like the tool to do.

**Comment by sayedihashimi** [comment]
@h3rmanj thanks for the comments. I agree that docs are an issue. Kathleen Dollard, who owns the Template Engine and dotnet new, is working on updating the docs. I’m going to be moving these docs over to docs.microsoft.com as well. 

Your suggestion of an info message is good. Issue is that the analyzer currently analyzes a single template and has no knowledge of previous templates. I’m hoping that this issue isn’t wide spread, this is the first that I’m seeing someone run into this issue. I’ll keep an eye out for this type of issue, and if it’s a common issue I’ll figure out a way to update the analyzer. I appreciate your comments and suggestions, please keep them coming.

**Comment by RehanSaeed** [comment]
It seems there are a few people who are not seeing templates appear in VS 16.10:

https://github.com/RehanSaeed/rehansaeed.github.io/issues/359

**Comment by RehanSaeed** [comment]
Solution templates now exist.
