### ISSUE TITLE
Visual Studio for Mac custom template Forms not showing

### ISSUE THREAD

**Issue by Gregory-Lange** [sayedihashimi/template-sample#74]
Hi, 

I have followed your guide and even looked over MS guides to build a run-able template however when i do the `dotnet pack` and then install the NuGet my form inputs do not show up that i have setup in the template.json file.  Below are my files i have in .template.config.  Any help would be wonderful.

template.json

```json
{
    "$schema": "http://json.schemastore.org/template",
    "author": "",
    "classifications": [ "Web", "Cloud" ],
    "identity": "AzureAD.MVC",
    "name": "AzureAD MVC",
    "groupIdentity": "AzureAD",
    "shortName": "azuremvc",
    "sourceName": "Template.MVC",
    "defaultName": "MyMVCUIApp",
    "tags": {
        "language": "C#",
        "type": "project",
        "vs_parametersToHide": "SkipRestore"
    },
    "preferNameDirectory": true,
    "symbols": {
        "ClientId": {
            "type": "parameter",
            "dataType": "string",
            "displayName": "AzureAD Application (client) ID",
            "defaultValue": "00000000-0000-0000-0000-000000000000",
            "replaces": "__CLIENTID__"
        },
        "TenantId": {
            "type": "parameter",
            "dataType": "string",
            "displayName": "AzureAD Directory (tenant) ID",
            "defaultValue": "00000000-0000-0000-0000-000000000000",
            "replaces": "__TENANTID__"
        },
        "ClientSecret": {
            "type": "parameter",
            "dataType": "string",
            "displayName": "AzureAD Client Secret",
            "defaultValue": "00000~0000000000000000000000000000000000",
            "replaces": "__CLIENTSECRET__"
        },
        "ApiScopes": {
            "type": "parameter",
            "dataType": "string",
            "displayName": "API Scopes (space delimited)",
            "defaultValue": "user.read",
            "replaces": "__APISCOPES__"
        },
        "SkipRestore": {
            "type": "parameter",
            "datatype": "bool",
            "description": "If specified, skips the automatic restore of the project on create.",
            "defaultValue": "false"
        }
    },
    "forms": {
        "uc": {
            "identifier":  "upperCase"
        }
    }
    "postActions": [
        {
            "condition": "(!skipRestore)",
            "description": "Restore NuGet packages required by this project.",
            "manualInstructions": [
                { "text": "Run 'dotnet restore'" }
            ],
            "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
            "continueOnError": true
        }
    ]
}
```

ide.host.json

```json
{
    "$schema": "http://json.schemastore.org/vs-2017.3.host",
    "name": { "text": "AzureAD MVC" },
    "defaultSymbolVisibility": true,
    "description": { "text": "This will allow Developers to make an MVC application that has all the wire-ups to start an application." },
    "icon": "icon.png",
    "tags": [
        {
            "type": "platform",
            "add": [ "C#", "MVC", "AzureAD" ]
        }
    ]
}
```

dotnetcli.host.json

```json
{
    "$schema": "http://json.schemastore.org/dotnetcli.host"
}
```

**Comment by sayedihashimi** [comment]
Hi @Gregory-Lange does your template appear and work in Visual Studio (windows)? If so, it should be working in VS for Mac as well.

**Comment by Gregory-Lange** [comment]
@sayedihashimi They do show up on my windows machine however do not on Mac.  I have validated i have VS for Mac updated to latest.  Did something change for the Mac silicon based version?

**Comment by Gregory-Lange** [comment]
@sayedihashimi I went back and added the symbols and isVisible to the ide.host.json file to see if for some reason VS for Mac on Apple Silicon was not updated yet but still nothing.

**Comment by sayedihashimi** [comment]
@Gregory-Lange I'm really not sure. If I understand correct, your template is appearing in VS for Mac, but the parameters are not showing up? We used to have a limitation that the template was required to have a `Framework` parameter (as described at https://github.com/sayedihashimi/template-sample#framework). Could you try to add a `Framework` parameter and try again to see if it works. FYI if you're installing from a .nupkg to test you may need to change the version of the package to ensure that cached files are not used.

**Comment by Gregory-Lange** [comment]
@sayedihashimi I will add the Framework parameter to it and change the version number and give it a try.  but you did understand the template shows up to be selected just the parameters will not show up to input but they do on Windows.  I will give the framework item a test and repot back to you.

**Comment by Gregory-Lange** [comment]
@sayedihashimi I added the framework and then moved version to one i haven't used yet and still the inputs for the parameters do not show up on VS for Mac.  I am on VS 2022 for Mac Version 17.6.

**Comment by Gregory-Lange** [comment]
To give you more information I created this template on my Mac and like i stated the forms show up on windows but not on Mac.  Is this an issue with the Mac version of VS?

**Comment by sayedihashimi** [comment]
@phenning do you have any ideas why parameters don't display in the New Project Dialog in VS for Mac?

**Comment by phenning** [comment]
@sayedihashimi I'm not sure, perhaps VSMac still requires specific visibility to be set on the symbolInfos. It may not support defaultSymbolVisibility.

@mrward might know more..

**Comment by phenning** [comment]
Oh, I see that you tried with explict isVisible after I typed my response.

@mrward any ideas?

**Comment by mrward** [comment]
VS Mac should show parameters from project templates. The ShinyApp project templates are one example that include parameters:

https://github.com/shinyorg/templates/blob/master/ProjectTemplates/ShinyApp/.template.config/template.json#L44
https://github.com/shinyorg/templates/blob/master/ProjectTemplates/ShinyApp/.template.config/ide.host.json#L13

![image](https://github.com/sayedihashimi/template-sample/assets/372361/d48c5ead-78ae-4bc8-b97d-08678a944308)

The ShinyApp has symbols defined in the template.json file and symbolInfo defined in the ide.host.json file. Maybe it is because symbolInfo is missing from the ide.host.json file? That is the only difference that I can see.

**Comment by mrward** [comment]
@Gregory-Lange Do you have a .nupkg available to test?

**Comment by Gregory-Lange** [comment]
@mrward Let me see if i can clean up my namespaces a bit and then i will make a new one double check its still not working and then upload it here for you.

**Comment by Gregory-Lange** [comment]
@mrward  Here is my the package.
[AzureAD.MVC.1.0.8.nupkg.zip](https://github.com/sayedihashimi/template-sample/files/12175999/AzureAD.MVC.1.0.8.nupkg.zip)

**Comment by mrward** [comment]
To get your project template to work I had to add the Framework symbol to the template.json.

```
    "symbols": {
        "Framework": {
            "type": "parameter",
            "description": "The target framework for the project.",
            "datatype": "choice",
            "choices": [{
                "choice": "net6.0",
                "description": "Target .NET 6.0"
            }],
            "replaces": "{DOTNET_TFM}",
            "defaultValue": "net6.0"
        },
        "ClientId": {
            "type": "parameter",
            "dataType": "string",
            "displayName": "AzureAD Application (client) ID",
            "defaultValue": "00000000-0000-0000-0000-000000000000",
            "replaces": "__CLIENTID__"
        },
```

Also .NET 6.0, in this case, needs to be installed since there seems to be some restriction in VS Mac where it will not show the project template wizard page if the frameworks supported by the template are not installed.

![image](https://github.com/sayedihashimi/template-sample/assets/372361/41a2a184-26b7-44f0-8d9f-26ba9a5e6226)

**Comment by Gregory-Lange** [comment]
Interesting so .VS for Mac still has that as a dependency where on windows its not.  That did the trick!  Thank you for helping on this.  I had it added before just not the first symbol on the list and it didn't work.  But thank you for this as it helps me out greatly!  If anything else comes up and i can't find documentation to tell me what i am missing or did wrong i will reach out again.
