### ISSUE TITLE
How to create the files conditionally using template.json

### ISSUE THREAD

**Issue by akhileshk9** [sayedihashimi/template-sample#75]
I have scenario where based on the user options selection, certain files should be hidden(not added to the project) or add files to the project. Please advice.

**Comment by sayedihashimi** [comment]
There is an older sample at https://github.com/dotnet/dotnet-template-samples/tree/master/03-optional-page which I believe should still work that demonstrates how to exclude a file.

**Comment by akhileshk9** [comment]
Thanks for the reply syed. I have more complex use case. It is as follows:
1. I have solution with multiple projects in it.
2. I need to exclude a folder in one of the project based on a parameter.
Eg:

Solution Structure:
SampleSolution
      ProjectName.Implementation
      ProjectName.Infrastructure
                Data
                    Cosmos
                          Interfaces
                             <Files>
                          Implementation
                             <Files>
                    SQL
                        <Files>

The "ProjectName" part in the above project name is replaced based on the project name given in the wizard. If the user selects the datasource as SQL, then cosmos folder in the infrastructure project should be excluded.

Below is snippet from template.json:

"Datasource":{
        "type": "parameter",
        "datatype": "choice",
        "choices": [
          {
            "choice": "Cosmos"
          },
          {
            "choice": "SQL"
          }
        ]
      }
    },
    "sources": [
      {
        "modifiers": [
          {
            "condition": "(Datasource == 'SQL')",
            "exclude": [
              "*.Infrastructure/Data/Cosmos"
            ]
          }
        ]
      }
    ]

**Comment by sayedihashimi** [comment]
I'm sorry I never replied here @akhileshk9 are you still working through this or did you figure it out?
